//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddmissionForm
    {
        public int AddmissionFormId { get; set; }
        public Nullable<int> StudentInfoId { get; set; }
        public Nullable<int> CollegeInfoId { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> SubjectsChoosenId { get; set; }
        public Nullable<int> DocumentSubmittedId { get; set; }
        public Nullable<int> AcademicYearId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string AdmissionFormNo { get; set; }
        public string RollNumber { get; set; }
        public string Stream { get; set; }
        public Nullable<int> CoachingCentreId { get; set; }
        public string Remark { get; set; }
    }
}
