//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionFormStep
    {
        public int AdmissionFormStepsId { get; set; }
        public Nullable<int> AddmissionFormId { get; set; }
        public Nullable<bool> Step1CollegeClass { get; set; }
        public Nullable<bool> Step2StudInfo { get; set; }
        public Nullable<bool> Step3ParentInfo { get; set; }
        public Nullable<bool> Step4AddressInfo { get; set; }
        public Nullable<bool> Step5SubjectSelection { get; set; }
        public Nullable<bool> Step6PrevAcademic { get; set; }
        public Nullable<bool> Step7DocumentSubmission { get; set; }
        public Nullable<bool> Step8 { get; set; }
        public Nullable<bool> Step9 { get; set; }
        public Nullable<bool> Step10 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
