//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssStudentParentInfo
    {
        public int AssStudentParentInfoId { get; set; }
        public Nullable<int> StudentInfoId { get; set; }
        public Nullable<int> ParentInfoId { get; set; }
        public string ParentType { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ParentInfo ParentInfo { get; set; }
    }
}
