//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeInfo
    {
        public int CollegeInfoId { get; set; }
        public string CollegeName { get; set; }
        public string CollegeType { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string ContactNo1 { get; set; }
        public string ContactNo2 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string LogoURL { get; set; }
        public string CollegeNameShort { get; set; }
    }
}
