//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentId { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public string ThumbnailLink { get; set; }
        public string ContainerName { get; set; }
        public string FileSize { get; set; }
        public string OtherDocumentType { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string Comment { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
