//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentSubmitted
    {
        public int DocumentSubmittedId { get; set; }
        public Nullable<int> AddmissionFormId { get; set; }
        public Nullable<bool> ClassXMarksheet { get; set; }
        public Nullable<bool> ClassXIMarksheet { get; set; }
        public Nullable<bool> SchoolLC { get; set; }
        public Nullable<bool> CasteCertificate { get; set; }
        public Nullable<bool> AadharCard { get; set; }
        public Nullable<bool> GapCertificate { get; set; }
        public Nullable<bool> SnglieGirlChild { get; set; }
        public Nullable<bool> ElegibilityCert { get; set; }
        public Nullable<bool> PassingCert { get; set; }
        public Nullable<bool> EBCCertificate { get; set; }
        public Nullable<bool> PassportSizePhoto { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> CopyOfLOC { get; set; }
        public Nullable<bool> AadharFather { get; set; }
        public Nullable<bool> AadharMother { get; set; }
    }
}
