//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeReceipt
    {
        public int FeeReceiptId { get; set; }
        public int AdmissionFormId { get; set; }
        public Nullable<decimal> AdmissionFee { get; set; }
        public Nullable<decimal> C1StInstallment { get; set; }
        public Nullable<decimal> C2ndInstallment { get; set; }
        public Nullable<decimal> C3rdInstallment { get; set; }
        public Nullable<decimal> C4thInstallment { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> ExamFee { get; set; }
        public Nullable<decimal> Misclellaneous { get; set; }
    }
}
