//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JaiHindEduEntitiesNew : DbContext
    {
        public JaiHindEduEntitiesNew()
            : base("name=JaiHindEduEntitiesNew")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AddmissionForm> AddmissionForms { get; set; }
        public virtual DbSet<AdmissionFormStep> AdmissionFormSteps { get; set; }
        public virtual DbSet<AssStudentAddressStudentInfo> AssStudentAddressStudentInfoes { get; set; }
        public virtual DbSet<AssStudentParentInfo> AssStudentParentInfoes { get; set; }
        public virtual DbSet<ClassInfo> ClassInfoes { get; set; }
        public virtual DbSet<CoachingCentre> CoachingCentres { get; set; }
        public virtual DbSet<CollegeInfo> CollegeInfoes { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentSubmitted> DocumentSubmitteds { get; set; }
        public virtual DbSet<LutAcademicYear> LutAcademicYears { get; set; }
        public virtual DbSet<LutDocumentType> LutDocumentTypes { get; set; }
        public virtual DbSet<ParentInfo> ParentInfoes { get; set; }
        public virtual DbSet<StudentAddressInfo> StudentAddressInfoes { get; set; }
        public virtual DbSet<StudentInfo> StudentInfoes { get; set; }
        public virtual DbSet<StudentPreviousAcademicInfo> StudentPreviousAcademicInfoes { get; set; }
        public virtual DbSet<SubjectsChoosen> SubjectsChoosens { get; set; }
        public virtual DbSet<FeeReceipt> FeeReceipts { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<UserActivityLog> UserActivityLogs { get; set; }
    
        public virtual ObjectResult<GetAllApplicantStudentsByStudentId_Result> GetAllApplicantStudentsByStudentId(Nullable<int> studentInfoId, string academicYear)
        {
            var studentInfoIdParameter = studentInfoId.HasValue ?
                new ObjectParameter("StudentInfoId", studentInfoId) :
                new ObjectParameter("StudentInfoId", typeof(int));
    
            var academicYearParameter = academicYear != null ?
                new ObjectParameter("AcademicYear", academicYear) :
                new ObjectParameter("AcademicYear", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllApplicantStudentsByStudentId_Result>("GetAllApplicantStudentsByStudentId", studentInfoIdParameter, academicYearParameter);
        }
    
        public virtual ObjectResult<GetAdmissionInfoByAddmissionFormId_Result> GetAdmissionInfoByAddmissionFormId(Nullable<int> addmissionFormId)
        {
            var addmissionFormIdParameter = addmissionFormId.HasValue ?
                new ObjectParameter("AddmissionFormId", addmissionFormId) :
                new ObjectParameter("AddmissionFormId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAdmissionInfoByAddmissionFormId_Result>("GetAdmissionInfoByAddmissionFormId", addmissionFormIdParameter);
        }
    }
}
