//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LutAcademicYear
    {
        public int AcademicYearId { get; set; }
        public string Year { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
    }
}
