//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LutDocumentType
    {
        public int DocumentTypeId { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsObsolete { get; set; }
        public string Category { get; set; }
    }
}
