//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParentInfo()
        {
            this.AssStudentParentInfoes = new HashSet<AssStudentParentInfo>();
        }
    
        public int ParentInfoId { get; set; }
        public string ParentType { get; set; }
        public string FullName { get; set; }
        public string Occupation { get; set; }
        public string AadharNo { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ParentPhotoId { get; set; }
        public Nullable<int> ParentSignatureId { get; set; }
        public string AnnualIncome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssStudentParentInfo> AssStudentParentInfoes { get; set; }
    }
}
