//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public int StudentInfoId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string AadharNo { get; set; }
        public Nullable<bool> IsSingleGirlChild { get; set; }
        public string BloodGroup { get; set; }
        public string Nationality { get; set; }
        public string Category { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string Domicile { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> StudentPhotoId { get; set; }
        public Nullable<int> StudentSignatureId { get; set; }
    }
}
