//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPreviousAcademicInfo
    {
        public int StudentPreviousAcademicInfoId { get; set; }
        public Nullable<int> StudentInfoId { get; set; }
        public string ExamName { get; set; }
        public string Board { get; set; }
        public string SchoolOrCollege { get; set; }
        public string ExamSeatNo { get; set; }
        public string EligibilityCertNo { get; set; }
        public string MonthYearOfPassing { get; set; }
        public string TotalMarks { get; set; }
        public string Percentage { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
