//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectsChoosen
    {
        public int SubjectsChoosenId { get; set; }
        public Nullable<int> AddmissionFormId { get; set; }
        public Nullable<bool> English { get; set; }
        public Nullable<bool> Physics { get; set; }
        public Nullable<bool> Chemistry { get; set; }
        public Nullable<bool> EVS { get; set; }
        public Nullable<bool> PhysicalEducation { get; set; }
        public Nullable<bool> Hindi { get; set; }
        public Nullable<bool> Marathi { get; set; }
        public Nullable<bool> Mathemcatics { get; set; }
        public Nullable<bool> Biology { get; set; }
        public Nullable<bool> Geography { get; set; }
        public Nullable<bool> ComputerScience { get; set; }
        public Nullable<bool> InformationTechnology { get; set; }
        public Nullable<bool> CropScience { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> InformaticsPractices { get; set; }
    }
}
