//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivityLog
    {
        public int UserActivityLogId { get; set; }
        public string UserName { get; set; }
        public string RoleName { get; set; }
        public string ActivityType { get; set; }
        public string EntityName { get; set; }
        public string EntityId { get; set; }
        public string Description { get; set; }
        public string BeforeValues { get; set; }
        public string AfterValues { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string Url { get; set; }
        public string HttpMethod { get; set; }
        public string IpAddress { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
