//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiHindEdutech.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public long UserPermissionId { get; set; }
        public long UserId { get; set; }
        public string ModuleKey { get; set; }
        public Nullable<bool> CanView { get; set; }
        public Nullable<bool> CanCreate { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> CanDelete { get; set; }
    }
}
